---
title: "Data visualisation"
output: distill::distill_article
css: "css/strapless.css"
---
<style type="text/css">
.main-container {
  max-width: 1600px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

### Work
```{r, layout="l-page"}
first <- read_csv("data/first_page.csv")
first %>% 
  filter(description == "Datavis") %>%
  bs4cards::cards(
    link = url,
    image = src,
    spacing = 4,
    tags = paste("all;", tag),
    #width = 2,
    width = "row-cols-2",
    border_width = 0,
    layout = "image-only",
    breakpoint = 5,
    #border_colour = "#ffffffaa"
    
  )
# slickR::slickR(
#     list.files("img/work/", full.names = TRUE, pattern = 'jpg'),
#     objLinks = c(NA, "Network.html", NA),
#     height = 400,
#     width = '95%') +
#   # (slickR(c(,
#   #           "Where my cv is going"), slideType = 'p') + 
#      settings(autoplay = TRUE)
```


<!-- # ```{r} -->
<!-- slickR( -->
<!--      list.files("img/published/",full.names = TRUE, pattern = 'jpg'), -->
<!--      objLinks = c("Topic_modeling.html", "Topic_modeling.html"), -->
<!--      height = 400, -->
<!--      width = '95%') + -->
<!--  #%synch% -->
<!--    # (slickR(c("How articles are connected each other with different subjects", -->
<!--    #           "Data art of chord diagram with watercolour"), slideType = 'p') + -->
<!--       settings(arrows = FALSE, autoplay = TRUE) -->
<!-- ``` -->



<!-- # ```{r} -->
<!-- # slickR( -->
<!-- #     list.files("img/personal/",full.names = TRUE, pattern = 'jpg'), -->
<!-- #     objLinks = c("World_fertility.html", -->
<!-- #                  "Solar_consuption.html"), -->
<!-- #     height = 400, -->
<!-- #     width = '95%') %synch% -->
<!-- #   (slickR(c("World fertility rate", -->
<!-- #             "Household solar consumption in Europe"), slideType = 'p') +  -->
<!-- #      settings(arrows = FALSE, autoplay = TRUE)) -->
<!-- ``` -->

