---
title: "Gallery"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(slickR)
```

# Work projects

<!-- ```{r} -->
<!-- #paths <- list.files("img/", full = TRUE) -->
<!-- pixture("_gallery/img/sankey2.jpg") -->

<!-- ``` -->

```{r}
slickR::slickR(
    list.files("img/work/",full.names = TRUE, pattern = 'png'),
    height = 400,
    width = '95%') +
  slickR::settings(autoplay = TRUE)
```

# Published

```{r}

slickR(
    list.files("img/published/",full.names = TRUE, pattern = 'png'),
    height = 400,
    width = '95%') +
  slickR::settings(autoplay = TRUE)
 # settings(infinite= TRUE,
 #          speed = 300,
 #          slidesPerRow = 2,
 #          centerMode = TRUE,
 #          variableWidth = TRUE) 
```


# Personal projects
```{r}
slickR(
    list.files("img/personal/",full.names = TRUE, pattern = 'png'),
    height = 400,
    width = '95%') +
  slickR::settings(autoplay = TRUE)
 # settings(infinite= TRUE,
 #          speed = 300,
 #          slidesPerRow = 2,
 #          centerMode = TRUE,
 #          variableWidth = TRUE) 
```



<!-- <head> -->

<!-- <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.0/css/lightgallery.min.css" /> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery-js/1.4.1-beta.0/js/lightgallery.min.js"></script> -->

<!-- <!-- lightgallery plugins --> 
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/lg-fullscreen/1.2.1/lg-fullscreen.min.js"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/lg-thumbnail/1.2.1/lg-thumbnail.min.js"></script> -->

<!-- </head> -->

<!-- ```{css} -->

<!-- .column { -->
<!--   float: left; -->
<!--   width: 45%; -->
<!--   margin-left: 1rem; -->
<!-- } -->
<!-- /* Clear floats after the columns */ -->
<!-- .row:after { -->
<!--   content: ""; -->
<!--   display: table; -->
<!--   clear: both; -->
<!-- } -->
<!-- #lightgallery > a > img:hover { -->
<!--    transform: scale(1.15, 1.15); -->
<!--    transition: 0.4s ease-in-out; -->
<!--    cursor: pointer; -->
<!-- } -->

<!-- /* For some reason, icons are not loaded so I choose them myself */ -->
<!-- .lg-actions .lg-next { -->
<!--   content:"\1433" -->
<!-- } -->
<!-- .lg-actions .lg-prev { -->
<!--   content:"\1438" -->
<!-- } -->
<!-- .lg-toolbar .lg-download { -->
<!--  content:"\2913" -->
<!-- } -->
<!-- .lg-toolbar .lg-close { -->
<!--  content:"\00D7" -->
<!-- } -->
<!-- .lg-toolbar .lg-icon { -->
<!-- 	background-color: #000; -->
<!-- 	border-color: #000; -->
<!-- 	border-style: solid; -->
<!-- } -->

<!-- ``` -->

<!-- ```{r include = FALSE} -->
<!-- # Load the functions we have created -->
<!-- source(here::here("resize.R")) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # Create layout -->
<!-- withTags( -->
<!--   div( -->
<!--     class = "row", -->
<!--     id = "lightgallery", -->
<!--     tagList( -->
<!--       make_gallery() -->
<!--     ) -->
<!--   ) -->
<!-- ) -->

<!-- ``` -->

<!-- <script type="text/javascript"> -->
<!--     lightGallery(document.getElementById('lightgallery'), { -->
<!--       hideBarsDelay: 1500 -->
<!--     });  -->
<!-- </script> -->



